class_name WorldMap extends Control
## Manages the visual display of the Map generated by a MapGenerator,
## And loading each event's scene.

@onready var map_generator:MapGenerator = $MapGenerator

## The parent of all buttons.
@onready var button_space := $MapGenerator/ScrollContainer/MarginContainer/PanelContainer
## The node under the scroll container; the one that needs a new minimum size.
@onready var scroll_node := $MapGenerator/ScrollContainer/MarginContainer

var event_buttons:Dictionary[Event, EventButton]

var current_row = 0

func _ready() -> void:
	map_generator.generate_map()
	
	
	update_visual()

func update_visual() -> void:
	
	## All the events that need representing.
	var events := map_generator.get_active_events()
	
	## Reassign the event buttons, making new ones and removing unused ones
	## as needed.
	
	var buttons := event_buttons.values() as Array[EventButton]
	event_buttons.clear()
	
	# Create any needed new buttons.
	while buttons.size() < events.size():
		var new_button := preload("res://scenes/event_button.tscn").instantiate() as EventButton
		
		button_space.add_child(new_button)
		
		buttons.append(new_button)
	
	# Rid thineself of any excess buttons.
	while buttons.size() > events.size(): buttons.pop_front().queue_free()
	
	# Offset to near the bottom of the screen, and so that the middle column is in the middle.
	var offset := Vector2(
		(button_space.custom_minimum_size.x / 2.) - map_generator.SPACING.x * floori(map_generator.config.map_width / 2.),
		map_generator.SPACING.y * (map_generator.config.floor_count)
		)
	
	# Reassign the buttons to their new events.
	for i in events.size():
		var this_button := buttons[i]
		var this_event  := events[i]
		
		if this_button.pressed.is_connected(_on_event_button_pressed):
			this_button.pressed.disconnect(_on_event_button_pressed)
		
		this_button.set_event(this_event)
		
		this_button.pressed.connect(_on_event_button_pressed.bind(this_button))
		
		# Start from near the bottom of the screen.
		this_button.position += offset
		
		event_buttons[this_event] = this_button
		
		# Unlock the first row.
		if this_event.row == 0: this_button.available = true
		
	
	scroll_node.custom_minimum_size.y = offset.y + (map_generator.SPACING.y * 2)
	

func _on_event_button_pressed(button:EventButton):
	current_row = button.event.row + 1
	
	for av_button in event_buttons.values(): av_button.available = false
	
	for event in button.event.next_options:
		event_buttons[event].available = true  
	
