class_name WorldMap extends Control
## Manages the visual display of the Map generated by a MapGenerator,
## And loading each event's scene.

const MUSIC_TRANSITIONS:Dictionary[Event.TYPE, String] = {
	Event.TYPE.COMBAT: "Combat"
}

@export var scene_parents:Dictionary[Event.TYPE, Node]
var current_event_scene:Node # The current node for the open event.
var current_event:Event

@onready var map_generator:MapGenerator = $MapGenerator

## The parent of all buttons.
@onready var button_space := $MapGenerator/ScrollContainer/PanelContainer
## The node under the scroll container; the one that needs a new minimum size.
@onready var scroll_node := $MapGenerator/ScrollContainer/PanelContainer

var event_buttons:Dictionary[Event, EventButton]
var lines:Array[Line2D]

var current_row = 0

func _ready() -> void:
	
	Global.act_changed.connect(_regenerate_map)
	_regenerate_map()

func _regenerate_map():
	map_generator.generate_map()
	
	update_visual()

func update_visual() -> void:
	
	## All the events that need representing.
	var events := map_generator.get_active_events()
	
	## Reassign the event buttons, making new ones and removing unused ones
	## as needed.
	
	var buttons := event_buttons.values() as Array[EventButton]
	event_buttons.clear()
	
	# Create any needed new buttons.
	while buttons.size() < events.size():
		var new_button := preload("res://scenes/event_button.tscn").instantiate() as EventButton
		
		button_space.add_child(new_button)
		
		buttons.append(new_button)
	
	# Rid thineself of any excess buttons.
	while buttons.size() > events.size(): buttons.pop_front().queue_free()
	
	# Offset to near the bottom of the screen, and so that the middle column is in the middle.
	var offset := Vector2(
		(button_space.size.x / 2.) - map_generator.SPACING.x * floori(map_generator.config.map_width / 2.),
		map_generator.SPACING.y * (map_generator.config.floor_count + 1)
		)
	
	var unused_lines:Array[Line2D] = lines.duplicate()
	lines.clear()
	
	# Reassign the buttons to their new events, and make lines.
	for i in events.size():
		var this_button := buttons[i]
		var this_event  := events[i]
		
		if this_button.pressed.is_connected(_on_event_button_pressed):
			this_button.pressed.disconnect(_on_event_button_pressed)
		
		this_button.set_event(this_event)
		
		this_button.pressed.connect(_on_event_button_pressed.bind(this_button))
		
		# Start from near the bottom of the screen.
		this_button.position += offset
		
		event_buttons[this_event] = this_button
		
		# Make lines from this event_button to the ones it goes to.
		var find_line := func() -> Line2D:
			if unused_lines.size() > 0: return unused_lines.pop_front()
			
			var new_line := preload("res://scenes/map_line.tscn").instantiate()
			
			button_space.add_child(new_line)
			
			new_line.position = Vector2.ZERO
			
			return new_line
		
		for next_event in this_event.next_options:
			var line := find_line.call() as Line2D
			
			# Get the line's direction, for offsetting to stop icon overlap.
			var offset_vector := this_button.position.direction_to(next_event.position + offset) * 24
			
			line.points = [this_button.position + offset_vector, next_event.position + offset - offset_vector]
			
			lines.append(line)
		
		# Unlock only the first row.
		this_button.available = this_event.row == 0
	
	# Discard any unused lines.
	for line in unused_lines: line.queue_free()
	
	scroll_node.custom_minimum_size.y = offset.y + (map_generator.SPACING.y * 2)
	

func _on_event_button_pressed(button:EventButton):
	
	## If this button isn't an option, we ain't doing nothing.
	if not button.available: return
	
	## If there's a event already running, don't you dare start another.
	if current_event_scene: return
	
	## Load the scene for the button.
	var scene := button.event.get_new_scene()
	if scene:
		current_event_scene = scene
		current_event = button.event
		
		# Add the scene to the corresponding parent
		scene_parents[button.event.type].add_child(scene)
		
		# Connect the scene's finish signal to the finishing function.
		recurs_find_event_scene(scene).event_finished.connect(_finish_event)
		
		TransitionManager.transition(self, scene if scene is CanvasItem else null)
		
		# Change the music if necessary
		if MUSIC_TRANSITIONS.has(button.event.type):
			Global.request_track_transition.emit(MUSIC_TRANSITIONS[button.event.type])
	
	## Open up the next slots.
	
	current_row = button.event.row + 1
	
	for av_button in event_buttons.values(): av_button.available = false
	
	for event in button.event.next_options:
		event_buttons[event].available = true  

func recurs_find_event_scene(from:Node) -> EventScene:
	if from is EventScene: return from
	
	for node in from.get_children():
		var result := recurs_find_event_scene(node)
		if result is EventScene: return result
	
	return null

func _finish_event() -> void: 
		
	# Transition back the music if needed
	if MUSIC_TRANSITIONS.has(current_event.type):
		Global.request_track_transition.emit("Map")
	
	# Transition the screen
	await TransitionManager.transition_screen(current_event_scene if current_event_scene is CanvasItem else null, self)
	
	# Free the event.
	current_event_scene.queue_free()
	current_event_scene = null
	current_event = null
